### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by dnzln** [dnzln/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by myCatsAccount** [comment]
LANGUAGES
Russian, Ukrainian and a little bit of English. 

SKILLS
HTML5 CSS3 SCSS JS ES6 OOP Linux CLI AJAX CLI GIT GITHUB Photoshop Zeplin Avocode

EDUCATION
09.2016 - 06.2020
NULES, Kiev
Computer engineering

10.2018 - 05.2019
Kottans Frontend Course
During the course, we covered various topics related to web development, starting with the basics of Git, HTML, CSS and JS, and ending with more advanced topics like OOP, WebSocket and Async JS.

ЯЗЫКИ
Русский, украинский и немного английского.

НАВЫКИ
HTML5 CSS3 SCSS JS ES6 OOP Linux CLI AJAX CLI GIT GITHUB Photoshop Zeplin Avocode

ОБРАЗОВАНИЕ
09.2016 - 06.2020
НУБИП, Киев
Компьютерная инженерия

10.2018 - 05.2019
Kottans Frontend Course
В ходе курса мы рассмотрели различные темы, связанные с веб-разработкой, начиная с основ Git, HTML, CSS и JS, и заканчивая более сложными темами, такими как ООП, WebSocket и Async JS.

**Comment by dnzln** [comment]
Niiiice!
