### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by dnzln** [dnzln/homepage#5]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by myCatsAccount** [comment]
Junior front-end developer
Binotel LLC
07.2020 – 11.2020
Kiev

- create and modify layout of pages for the site, client web interfaces, landing pages;
- adaptation of the layout for different browsers and devices;
- interacting with the DOM using Javascript / jQuery;
- work with the design mock up.

10.2018
Started free Kottans Frontend Course. Great way to start your way as a developer, these guys are really awesome!

Webmaster
Online store vishnya.org.ua
09.2017 - 07.2020
Kiev

-  creation of several online stores;
-  content managment and technical optimization;
-  SEO promotion.

Three sites were created and filled with products, synchronization with trading platforms such as Rozetka was set up, optimization and SEOpromotion were carried out.

09.2016
You're in the university now,
Oh-oo-oh you're in the university now
(not today, army, not todat!)

Corywriter 
At different places at different time (is it really matter?)
Work at my own site made me a skilled corywriter, so it was my main daily bread for a few years.

02.2013
Build my first site on ucoz platform. It will migraite to Wordpress lately, but in is absolutly another story. 

What I learned working on the site:
- website development on Wordpress;
- creation of a semantic core;
- creating content for the site;
- work on site optimization, promotion.

At the peak, the average attendance of the resource was more than 50,000 people per month, the main traffic came from search engines and bookmarks.

Младший front-end разработчик
ООО «Бинотель»
07.2020 - 11.2020
Киев

- кроссбраузерная валидная верстка;
- верстка страниц для сайта, клиентских веб-интерфейсов, лендингов;
- адаптация верстки под различные браузеры и устройства;
- взаимодействие с DOM при помощи Javascript / jQuery;
- работа с макетом дизайна.

10.2018
Я попал на бесплатный Frontend-курс от Kottans. Отличный способ начать свой путь разработчика, эти ребята действительно классные!

Веб-мастер
Интернет-магазин vishnya.org.ua
09.2017 - 07.2020
Киев

- создание нескольких интернет-магазинов;
- наполнение контентом и техническая оптимизация;
- seo-продвижение сайта;
- многие другие технические задачи по обеспечению работы интернет-магазина.

Созданы и наполнены продуктами три сайта, настроена синхронизация с торговыми площадками типа Rozetka, проведена оптимизация и SEO-продвижение.

09.2016
Ты сейчас в университете,
О-о-о, ты сейчас в университете
(не сегодня, армия, не сегодня!)

Corywriter
В разных местах и в разное время (так ли важны даты?)
Работа над своим сайтом сделала меня неплохим копирайтером, так что несколько лет это был мой главный хлеб насущный.

02.2013
Создал свой первый сайт на платформе ucoz. Позже он переедет на Wordpress, но это совершенно другая история.

Чему я научился, работая над сайтом:
- создание сайта на Wordpress;
- создание семантического ядра;
- создание контента для сайта;
- работа над оптимизацией сайта, продвижение в ПС.

На пике средняя посещаемость ресурса составляла более 50 000 человек в месяц, основной трафик приходился с поисковых систем и закладок.
