### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by dnzln** [dnzln/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by myCatsAccount** [comment]
https://www.facebook.com/daniil.tkalenko
https://t.me/dnzln
dan.tkalenko@gmail.com
https://github.com/dnzln
https://www.linkedin.com/in/daniel-tkalenko/
