### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by dnzln** [dnzln/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by myCatsAccount** [comment]
Junior front-end developer with experience in related fields, such as creating and configuring sites using various CMS, SEO-optimization and content management.

Junior front-end разработчик с опытом в смежных областях, таких как создание и настройка сайтов на разных платформах и CMS, SEO-оптимизация и контент-менеджмент.
